#############################################################################
# Makefile for building: RandLib
# Generated by qmake (3.0) (Qt 5.6.2)
# Project:  RandLib.pro
# Template: lib
# Command: C:\Users\ASamarin\Anaconda3\Library\bin\qmake.exe -spec win32-g++ "CONFIG+=debug" -o Makefile RandLib.pro
#############################################################################

MAKEFILE      = Makefile

first: debug
install: debug-install
uninstall: debug-uninstall
QMAKE         = C:\Users\ASamarin\Anaconda3\Library\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		debug \
		release


debug: FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall
release: FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall

Makefile: RandLib.pro ../../../Anaconda3/Library/mkspecs/win32-g++/qmake.conf ../../../Anaconda3/Library/mkspecs/features/spec_pre.prf \
		../../../Anaconda3/Library/mkspecs/qdevice.pri \
		../../../Anaconda3/Library/mkspecs/features/device_config.prf \
		../../../Anaconda3/Library/mkspecs/common/angle.conf \
		../../../Anaconda3/Library/mkspecs/qconfig.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_3drender.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_axbase.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_axbase_private.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_axcontainer.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_axcontainer_private.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_axserver.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_axserver_private.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_core.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_core_private.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_dbus.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_designer.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_enginio.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_gui.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_help.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_help_private.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_labscontrols_private.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_labstemplates_private.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_location.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_location_private.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_network.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_network_private.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_nfc.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_opengl.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_positioning.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_qml.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_quick.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_script.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_script_private.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_sensors.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_serialport.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_sql.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_svg.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_testlib.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_uitools.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_webkit.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_websockets.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_widgets.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_winextras.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_winextras_private.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_xml.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Anaconda3/Library/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Anaconda3/Library/mkspecs/features/qt_functions.prf \
		../../../Anaconda3/Library/mkspecs/features/qt_config.prf \
		../../../Anaconda3/Library/mkspecs/features/win32/qt_config.prf \
		../../../Anaconda3/Library/mkspecs/win32-g++/qmake.conf \
		../../../Anaconda3/Library/mkspecs/features/spec_post.prf \
		../../../Anaconda3/Library/mkspecs/features/exclusive_builds.prf \
		../../../Anaconda3/Library/mkspecs/features/default_pre.prf \
		../../../Anaconda3/Library/mkspecs/features/win32/default_pre.prf \
		../../../Anaconda3/Library/mkspecs/features/resolve_config.prf \
		../../../Anaconda3/Library/mkspecs/features/exclusive_builds_post.prf \
		../../../Anaconda3/Library/mkspecs/features/default_post.prf \
		../../../Anaconda3/Library/mkspecs/features/win32/rtti.prf \
		../../../Anaconda3/Library/mkspecs/features/precompile_header.prf \
		../../../Anaconda3/Library/mkspecs/features/warn_on.prf \
		../../../Anaconda3/Library/mkspecs/features/file_copies.prf \
		../../../Anaconda3/Library/mkspecs/features/win32/windows.prf \
		../../../Anaconda3/Library/mkspecs/features/testcase_targets.prf \
		../../../Anaconda3/Library/mkspecs/features/exceptions.prf \
		../../../Anaconda3/Library/mkspecs/features/yacc.prf \
		../../../Anaconda3/Library/mkspecs/features/lex.prf \
		RandLib.pro
	$(QMAKE) -spec win32-g++ "CONFIG+=debug" -o Makefile RandLib.pro
../../../Anaconda3/Library/mkspecs/features/spec_pre.prf:
../../../Anaconda3/Library/mkspecs/qdevice.pri:
../../../Anaconda3/Library/mkspecs/features/device_config.prf:
../../../Anaconda3/Library/mkspecs/common/angle.conf:
../../../Anaconda3/Library/mkspecs/qconfig.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_3dcore.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_3dinput.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_3dlogic.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_3dquick.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_3drender.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_3drender_private.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_axbase.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_axbase_private.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_axcontainer.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_axcontainer_private.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_axserver.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_axserver_private.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_clucene_private.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_concurrent.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_core.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_core_private.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_dbus.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_designer.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_designer_private.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_enginio.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_enginio_private.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_gui.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_gui_private.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_help.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_help_private.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_labscontrols_private.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_labstemplates_private.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_location.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_location_private.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_multimedia.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_network.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_network_private.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_nfc.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_opengl.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_positioning.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_printsupport.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_qml.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_qml_private.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_qmltest.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_quick.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_quick_private.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_script.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_script_private.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_scripttools.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_sensors.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_serialbus.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_serialport.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_sql.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_sql_private.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_svg.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_svg_private.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_testlib.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_uitools.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_webchannel.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_webkit.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_webkit_private.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_websockets.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_widgets.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_winextras.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_winextras_private.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_xml.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_xml_private.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Anaconda3/Library/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Anaconda3/Library/mkspecs/features/qt_functions.prf:
../../../Anaconda3/Library/mkspecs/features/qt_config.prf:
../../../Anaconda3/Library/mkspecs/features/win32/qt_config.prf:
../../../Anaconda3/Library/mkspecs/win32-g++/qmake.conf:
../../../Anaconda3/Library/mkspecs/features/spec_post.prf:
../../../Anaconda3/Library/mkspecs/features/exclusive_builds.prf:
../../../Anaconda3/Library/mkspecs/features/default_pre.prf:
../../../Anaconda3/Library/mkspecs/features/win32/default_pre.prf:
../../../Anaconda3/Library/mkspecs/features/resolve_config.prf:
../../../Anaconda3/Library/mkspecs/features/exclusive_builds_post.prf:
../../../Anaconda3/Library/mkspecs/features/default_post.prf:
../../../Anaconda3/Library/mkspecs/features/win32/rtti.prf:
../../../Anaconda3/Library/mkspecs/features/precompile_header.prf:
../../../Anaconda3/Library/mkspecs/features/warn_on.prf:
../../../Anaconda3/Library/mkspecs/features/file_copies.prf:
../../../Anaconda3/Library/mkspecs/features/win32/windows.prf:
../../../Anaconda3/Library/mkspecs/features/testcase_targets.prf:
../../../Anaconda3/Library/mkspecs/features/exceptions.prf:
../../../Anaconda3/Library/mkspecs/features/yacc.prf:
../../../Anaconda3/Library/mkspecs/features/lex.prf:
RandLib.pro:
qmake: FORCE
	@$(QMAKE) -spec win32-g++ "CONFIG+=debug" -o Makefile RandLib.pro

qmake_all: FORCE

make_first: debug-make_first release-make_first  FORCE
all: debug-all release-all  FORCE
clean: debug-clean release-clean  FORCE
	-$(DEL_FILE) libRandLib.a
distclean: debug-distclean release-distclean  FORCE
	-$(DEL_FILE) Makefile

check: first

benchmark: first
FORCE:

$(MAKEFILE).Debug: Makefile
$(MAKEFILE).Release: Makefile
